serverName = "catirclogs.org"

[net.ipv6]
address = "2a01:4f8:c012:6185::1"
gateway = "fe80::1"

[net.ipv4]
address = "78.47.223.64"
gateway = "172.31.1.1"

[dns]
servers = ["2620:fe::fe", "9.9.9.9"]

[ssh]
pubkeys = [
  "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIC3Cn89kCKoRHtTt9ailswSbnO/PeqA70HUcbhzL3mml whitequark",
]

[web]
acmeEmail = "admin@catirclogs.org"
banner = """
<title>catirclogs.org</title>
<style>dt { font-weight: bold; }</style>
<h1>Catherine's IRC Logs</h1>
<p>Please email <a href="mailto:admin@catirclogs.org">admin@catirclogs.org</a> if you have an inquiry related to this server or its services. The administrators of this server are <a href="mailto:whitequark@whitequark.org">Catherine</a>.</p>
<p>This server hosts the following services:</p>
<dl>
  <dt>None at the moment</dt>
  <dd>
    This server is in the process of being deployed.
  </dd>
</dl>
"""

[backup]
enable = true
